In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import os
from google.colab import drive
drive.mount('/content/drive')

path = "/content/drive/MyDrive/lecture/"
os.listdir(path)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


['movies.csv',
 'ratings.csv',
 'tags.csv',
 'links.csv',
 'movie_user.gsheet',
 '제목 없는 문서.gdoc',
 '협업 필터링 - Item-based.ipynb',
 'movies_refined.csv',
 'ratings_refined.csv',
 '무비렌즈 데이터 전처리.ipynb',
 '협업 필터링 - User-based.ipynb',
 '협업_필터링_Item_based_ipynb의_사본.ipynb',
 'Jacquard.csv',
 'Jacquard(mean).csv',
 'user_means(x).ipynb',
 'user_means(x).ipynb의 사본',
 'mode.ipynb',
 'zero.ipynb',
 'euclidean_similarity_movies.csv',
 'euclidean_similarity.ipynb',
 'movie_user.csv',
 'Untitled0.ipynb',
 '협업 필터링 - User-based with dot production.ipynb',
 'Untitled0(x).ipynb',
 'euclidean_mode.ipynb',
 'euclidean_knn.ipynb',
 'user_based_cf_prediction.csv',
 'Untitled1.ipynb',
 'euclidean_mean.ipynb']

In [3]:
import pandas as pd
import numpy as np

In [4]:
ratings = pd.read_csv(path + "ratings_refined.csv", usecols=['userId', 'movieId', 'rating'])

In [5]:
movies = pd.read_csv(path + "movies_refined.csv", usecols=['movieId', 'title'])

In [6]:
df = pd.merge(ratings, movies, on='movieId', how='left')

In [7]:
df.columns[df.isna().any()].tolist()

[]

In [8]:
df[df['title'].isnull()]

Empty DataFrame
Columns: [userId, movieId, rating, title]
Index: []

In [9]:
movie_user = df.pivot_table(values='rating', index='title', columns='userId')
movie_user.to_csv('movie_user.csv')
movie_user

userId                              1    2    3    4    5    6    7    8    \
title                                                                        
'71                                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
'Hellboy': The Seeds of Creation    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
'Round Midnight                     NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
'Salem's Lot                        NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
'Til There Was You                  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
...                                 ...  ...  ...  ...  ...  ...  ...  ...   
eXistenZ                            NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
xXx                                 NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
xXx: State of the Union             NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
¡Three Amigos!                      4.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN   
À nous la liberté (Freedom for Us)  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   

userId                              9    10   ...  601  602  603  604  605  \
title                                         ...                            
'71                                 NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
'Hellboy': The Seeds of Creation    NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
'Round Midnight                     NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
'Salem's Lot                        NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
'Til There Was You                  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
...                                 ...  ...  ...  ...  ...  ...  ...  ...   
eXistenZ                            NaN  NaN  ...  NaN  NaN  5.0  NaN  NaN   
xXx                                 1.0  NaN  ...  NaN  NaN  NaN  NaN  NaN   
xXx: State of the Union             NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
¡Three Amigos!                      NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   
À nous la liberté (Freedom for Us)  NaN  NaN  ...  NaN  NaN  NaN  NaN  NaN   

userId                              606  607  608  609  610  
title                                                        
'71                                 NaN  NaN  NaN  NaN  4.0  
'Hellboy': The Seeds of Creation    NaN  NaN  NaN  NaN  NaN  
'Round Midnight                     NaN  NaN  NaN  NaN  NaN  
'Salem's Lot                        NaN  NaN  NaN  NaN  NaN  
'Til There Was You                  NaN  NaN  NaN  NaN  NaN  
...                                 ...  ...  ...  ...  ...  
eXistenZ                            NaN  NaN  4.5  NaN  NaN  
xXx                                 NaN  NaN  3.5  NaN  2.0  
xXx: State of the Union             NaN  NaN  NaN  NaN  1.5  
¡Three Amigos!                      NaN  NaN  NaN  NaN  NaN  
À nous la liberté (Freedom for Us)  NaN  NaN  NaN  NaN  NaN  

[9413 rows x 610 columns]

In [10]:
movie_user.shape

(9413, 610)

In [11]:
from sklearn.metrics.pairwise import euclidean_distances

# 결측값을 평균 값으로 대체
movie_user_tmp = movie_user.copy()
movie_user_tmp = movie_user_tmp.fillna(movie_user_tmp.mean())

# 유사도 행렬 계산
euclidean_similarity_matrix = 1 / (1 + euclidean_distances(movie_user_tmp, movie_user_tmp))

# 유사도 행렬 출력
print("Similarity Matrix:")
print(euclidean_similarity_matrix)

Similarity Matrix:
[[1.         0.66296876 0.65538492 ... 0.21104587 0.16703727 0.24142265]
 [0.66296876 1.         0.60711015 ... 0.21932644 0.16686198 0.24084285]
 [0.65538492 0.60711015 1.         ... 0.21920458 0.16681168 0.24067696]
 ...
 [0.21104587 0.21932644 0.21920458 ... 1.         0.14073457 0.17480748]
 [0.16703727 0.16686198 0.16681168 ... 0.14073457 1.         0.14540302]
 [0.24142265 0.24084285 0.24067696 ... 0.17480748 0.14540302 1.        ]]


In [12]:
euclidean_similarity_matrix

array([[1.        , 0.66296876, 0.65538492, ..., 0.21104587, 0.16703727,
        0.24142265],
       [0.66296876, 1.        , 0.60711015, ..., 0.21932644, 0.16686198,
        0.24084285],
       [0.65538492, 0.60711015, 1.        , ..., 0.21920458, 0.16681168,
        0.24067696],
       ...,
       [0.21104587, 0.21932644, 0.21920458, ..., 1.        , 0.14073457,
        0.17480748],
       [0.16703727, 0.16686198, 0.16681168, ..., 0.14073457, 1.        ,
        0.14540302],
       [0.24142265, 0.24084285, 0.24067696, ..., 0.17480748, 0.14540302,
        1.        ]])

In [13]:
movie_titles = movie_user.index
movie_titles

Index([''71', ''Hellboy': The Seeds of Creation', ''Round Midnight',
       ''Salem's Lot', ''Til There Was You', ''Tis the Season for Love',
       ''burbs, The', ''night Mother', '(500) Days of Summer',
       '*batteries not included',
       ...
       'Zulu', '[REC]', '[REC]²', '[REC]³ 3 Génesis',
       'anohana: The Flower We Saw That Day - The Movie', 'eXistenZ', 'xXx',
       'xXx: State of the Union', '¡Three Amigos!',
       'À nous la liberté (Freedom for Us)'],
      dtype='object', name='title', length=9413)

In [14]:
movie_similarity = pd.DataFrame(euclidean_similarity_matrix,
                                index=movie_titles, columns=movie_titles)
print(movie_similarity.shape)
movie_similarity

(9413, 9413)


title                                    '71  \
title                                          
'71                                 1.000000   
'Hellboy': The Seeds of Creation    0.662969   
'Round Midnight                     0.655385   
'Salem's Lot                        0.470307   
'Til There Was You                  0.435025   
...                                      ...   
eXistenZ                            0.193488   
xXx                                 0.150022   
xXx: State of the Union             0.211046   
¡Three Amigos!                      0.167037   
À nous la liberté (Freedom for Us)  0.241423   

title                               'Hellboy': The Seeds of Creation  \
title                                                                  
'71                                                         0.662969   
'Hellboy': The Seeds of Creation                            1.000000   
'Round Midnight                                             0.607110   
'Salem's Lot                                                0.464296   
'Til There Was You                                          0.430541   
...                                                              ...   
eXistenZ                                                    0.193206   
xXx                                                         0.152036   
xXx: State of the Union                                     0.219326   
¡Three Amigos!                                              0.166862   
À nous la liberté (Freedom for Us)                          0.240843   

title                               'Round Midnight  'Salem's Lot  \
title                                                               
'71                                        0.655385      0.470307   
'Hellboy': The Seeds of Creation           0.607110      0.464296   
'Round Midnight                            1.000000      0.462621   
'Salem's Lot                               0.462621      1.000000   
'Til There Was You                         0.429283      0.607287   
...                                             ...           ...   
eXistenZ                                   0.193126      0.188856   
xXx                                        0.151998      0.149987   
xXx: State of the Union                    0.219205      0.212830   
¡Three Amigos!                             0.166812      0.164120   
À nous la liberté (Freedom for Us)         0.240677      0.232103   

title                               'Til There Was You  \
title                                                    
'71                                           0.435025   
'Hellboy': The Seeds of Creation              0.430541   
'Round Midnight                               0.429283   
'Salem's Lot                                  0.607287   
'Til There Was You                            1.000000   
...                                                ...   
eXistenZ                                      0.187145   
xXx                                           0.149165   
xXx: State of the Union                       0.210319   
¡Three Amigos!                                0.163026   
À nous la liberté (Freedom for Us)            0.228779   

title                               'Tis the Season for Love  'burbs, The  \
title                                                                       
'71                                                 0.358777     0.186590   
'Hellboy': The Seeds of Creation                    0.356542     0.186340   
'Round Midnight                                     0.355909     0.187625   
'Salem's Lot                                        0.326191     0.182458   
'Til There Was You                                  0.316002     0.180926   
...                                                      ...          ...   
eXistenZ                                            0.181367     0.142827   
xXx                                                 0.146313     0.126962   
xXx: State of t

In [15]:
movie_similarity = pd.DataFrame(euclidean_similarity_matrix,
                                index=movie_titles, columns=movie_titles)

# 샘플 영화에 대한 유사한 영화 찾기
sample_movie = "¡Three Amigos!"  # 여기에 샘플 영화 제목을 넣어주세요
similar_movies = movie_similarity[sample_movie].sort_values(ascending=False)[1:10]

# 결과 출력
print(similar_movies)

title
Oh, God!                                 0.186819
Care Bears Movie, The                    0.186241
Care Bears Movie II: A New Generation    0.186241
Darby O'Gill and the Little People       0.178570
Puppet Masters, The                      0.174765
Fantastic Voyage                         0.174738
Innerspace                               0.173376
House Party                              0.172850
My Life                                  0.172433
Name: ¡Three Amigos!, dtype: float64


In [ ]:
from tqdm.notebook import tqdm

# 예측을 위한 함수
def modeling(similarity_matrix, data):
    # 데이터 프레임 초기화 및 사용자 및 영화 정보 추출
    df_pred_all = pd.DataFrame()
    user_ids = sorted(data['userId'].unique())
    all_movies = similarity_matrix.index
    n_movies = len(all_movies)

    for user_id in tqdm(user_ids):
        idx = data[data['userId'] == user_id].index

        # 현재 사용자가 이미 시청한 영화들에 대한 유사도 행렬 추출
        watched_movie_ids = data.loc[idx, 'title'].tolist()
        sub_sim_mat = similarity_matrix.loc[watched_movie_ids]
        sub_sim_mat = sub_sim_mat.T.to_numpy()

        # 유사도에 대한 정규화 항 계산
        sim_N = np.sum(sub_sim_mat, axis=1) + 1  # 1을 더하는 이유 => 유사도의 합이 0이 되는 경우를 방지

        # 현재 사용자가 시청한 영화에 대한 평점 가져오기
        watched_movie_ratings = data.loc[idx, 'rating']
        watched_movie_ratings = np.array(watched_movie_ratings.tolist()).reshape(-1, 1)

        # 가중 평균을 사용하여 평점 예측
        pred_y = np.matmul(sub_sim_mat, watched_movie_ratings).flatten() / sim_N

        user_id_list = [user_id] * n_movies
        cur_pred = pd.DataFrame(zip(user_id_list, all_movies, pred_y),
                                columns=['userId', 'title', 'pred_rating'])

        # 결과 기록
        df_pred_all = pd.concat([df_pred_all, cur_pred], axis=0)

    return df_pred_all

# 예시 사용
df_pred_all = modeling(movie_similarity, df)


  0%|          | 0/610 [00:00<?, ?it/s]

In [ ]:
df_pred_all

userId                               title  pred_rating
0          1                                 '71     4.251603
1          1    'Hellboy': The Seeds of Creation     4.251724
2          1                     'Round Midnight     4.251955
3          1                        'Salem's Lot     4.249073
4          1                  'Til There Was You     4.247855
...      ...                                 ...          ...
9408     610                            eXistenZ     3.631722
9409     610                                 xXx     3.587341
9410     610             xXx: State of the Union     3.552874
9411     610                      ¡Three Amigos!     3.627440
9412     610  À nous la liberté (Freedom for Us)     3.624820

[5741930 rows x 3 columns]

In [ ]:
def get_unwatched_movies(user_id, watched_movies, all_movies):
    unwatched_movies = set(all_movies) - set(watched_movies)
    num_unwatched_movies = len(unwatched_movies)
    return list(unwatched_movies), num_unwatched_movies

# 예시 사용
user_id_to_check = 1  # 사용자 ID를 적절히 설정
watched_movies_by_user = df[df['userId'] == user_id_to_check]['title'].tolist() #해당 사용자가 이미 시청한 영화 목록이 저장
all_movies_list = df['title'].unique().tolist() #전체 영화 목록이 저장

#함수를 호출하여 사용자가 아직 보지 않은 영화 목록과 그 수 출력
unwatched_movies_list, num_unwatched_movies = get_unwatched_movies(user_id_to_check, watched_movies_by_user, all_movies_list)

# 처음 10개의 영화만 출력
print(f"총 {num_unwatched_movies}개의 영화가 남아있습니다.")
print(f"사용자 {user_id_to_check}가 아직 보지 않은 영화 목록:")
for movie in unwatched_movies_list[:10]:
    print(movie)

총 9184개의 영화가 남아있습니다.
사용자 1가 아직 보지 않은 영화 목록:
Three Wishes
Dunkirk
Hercules
Illusionist, The
Arthur 2: On the Rocks
Jimmy Carr: Making People Laugh
Zelary
Mean Machine
Holes
My Blueberry Nights


In [ ]:
def recommend_top_movies_for_user(user_id, df_user, df_pred, top_n=10):
    # 사용자가 이미 본 영화 목록 가져오기
    watched_movies_by_user = df_user[df_user['userId'] == user_id]['title'].tolist()

    # 모든 영화 목록 가져오기
    all_movies_list = df_user['title'].unique().tolist()

    # 사용자가 아직 보지 않은 영화 목록 가져오기
    unwatched_movies_list, _ = get_unwatched_movies(user_id, watched_movies_by_user, all_movies_list)

    # 사용자가 아직 보지 않은 영화 중에서 pred_rating이 높은 상위 N개 영화 추천
    user_pred_data = df_pred[df_pred['userId'] == user_id]
    unwatched_movies_pred = user_pred_data[user_pred_data['title'].isin(unwatched_movies_list)]

    # 평점이 높은 상위 N개 영화 추천
    top_movies = unwatched_movies_pred.sort_values(by='pred_rating', ascending=False).head(top_n)

    return top_movies[['title', 'pred_rating']].values.tolist()

# 사용자가 아직 보지 않은 영화 중에서 pred_rating이 높은 상위 10개 추천 받기
user_id_to_recommend = 1  # 사용자 ID를 적절히 설정
recommended_movies = recommend_top_movies_for_user(user_id_to_recommend, df, df_pred_all, top_n=10)

# 결과 출력
print(f"사용자 {user_id_to_recommend}에게 추천되는 영화:")
for movie, pred_rating in recommended_movies:
    print(f"{movie} - 예측 평점: {pred_rating}")

사용자 1에게 추천되는 영화:
Ararat - 예측 평점: 4.259101316324397
Copenhagen - 예측 평점: 4.259101316324397
A Most Wanted Man - 예측 평점: 4.259101316324397
The Square - 예측 평점: 4.258945254424639
Liberty Heights - 예측 평점: 4.258144109751988
It Might Get Loud - 예측 평점: 4.25809388989759
Rain - 예측 평점: 4.25792644392628
Cherish - 예측 평점: 4.25792644392628
Two Family House - 예측 평점: 4.25792644392628
All the Real Girls - 예측 평점: 4.257851588979614


In [ ]:
def recommend_top_movies_for_user_input(user_id, df_user, df_pred, top_n=10):
    # 사용자가 이미 본 영화 목록 가져오기
    watched_movies_by_user = df_user[df_user['userId'] == user_id]['title'].tolist()

    # 모든 영화 목록 가져오기
    all_movies_list = df_user['title'].unique().tolist()

    # 사용자가 아직 보지 않은 영화 목록 가져오기
    unwatched_movies_list, _ = get_unwatched_movies(user_id, watched_movies_by_user, all_movies_list)

    # 사용자가 아직 보지 않은 영화 중에서 pred_rating이 높은 상위 N개 영화 추천
    user_pred_data = df_pred[df_pred['userId'] == user_id]
    unwatched_movies_pred = user_pred_data[user_pred_data['title'].isin(unwatched_movies_list)]

    # 평점이 높은 상위 N개 영화 추천
    top_movies = unwatched_movies_pred.sort_values(by='pred_rating', ascending=False).head(top_n)

    return top_movies[['title', 'pred_rating']].values.tolist()

# 사용자로부터 입력 받기
user_id_to_recommend = int(input("사용자 ID를 입력하세요: "))

# 사용자가 아직 보지 않은 영화 중에서 pred_rating이 높은 상위 10개 추천 받기
recommended_movies = recommend_top_movies_for_user_input(user_id_to_recommend, df, df_pred_all, top_n=10)

# 결과 출력
print(f"사용자 {user_id_to_recommend}에게 추천되는 영화:")
for movie, pred_rating in recommended_movies:
    print(f"{movie} - 예측 평점: {pred_rating}")

사용자 ID를 입력하세요: 100
사용자 100에게 추천되는 영화:
Imitation of Life - 예측 평점: 3.8416017181708204
Anna Karenina - 예측 평점: 3.8404158132492117
Washington Square - 예측 평점: 3.840344289784246
Stage Fright - 예측 평점: 3.8399966020621963
Grass Is Greener, The - 예측 평점: 3.8399148068357327
Send Me No Flowers - 예측 평점: 3.8399148068357327
Secret of My Succe$s, The (a.k.a. The Secret of My Success) - 예측 평점: 3.83963984851843
Man Who Cried, The - 예측 평점: 3.839475360688123
Land of Plenty (Angst and Alienation in America) - 예측 평점: 3.8394537334574856
Kiss Me, Stupid - 예측 평점: 3.8394537334574856


In [ ]:
from sklearn.model_selection import train_test_split #데이터를 나누는 작업을 수행

_, test_data = train_test_split(df[['userId', 'title', 'rating']], #데이터프레임에서 'userId', 'title', 'rating' 열만 선택한 부분집합
                test_size=20000, random_state=1234, stratify=df['userId'])
 #test_size 테스트 데이터의 크기를 지정 / random_state 난수 발생 시 사용되는 시드(seed) 값 / 계층화 샘플링을 수행

test_data

userId                                       title  rating
72039     464                            Escape from L.A.     3.0
90528     590                               Carlito's Way     4.0
20360     135             Nightmare Before Christmas, The     4.0
42826     288     Naked Gun 2 1/2: The Smell of Fear, The     4.0
37923     258                   Guardians of the Galaxy 2     3.5
...       ...                                         ...     ...
94958     599                              Thor: Ragnarok     3.0
63609     414  Revenge of the Nerds II: Nerds in Paradise     2.0
68727     448                             Wild Bunch, The     5.0
38371     263                                Gosford Park     4.5
42381     288                                        Bean     3.0

[20000 rows x 3 columns]

In [ ]:
test_data = pd.merge(test_data, df_pred_all, on=['userId', 'title'], how='left')
test_data

userId                                       title  rating  pred_rating
0         464                            Escape from L.A.     3.0     3.336239
1         590                               Carlito's Way     4.0     3.326141
2         135             Nightmare Before Christmas, The     4.0     3.478600
3         288     Naked Gun 2 1/2: The Smell of Fear, The     4.0     3.088397
4         258                   Guardians of the Galaxy 2     3.5     3.024585
...       ...                                         ...     ...          ...
19995     599                              Thor: Ragnarok     3.0     2.595451
19996     414  Revenge of the Nerds II: Nerds in Paradise     2.0     3.271710
19997     448                             Wild Bunch, The     5.0     2.834853
19998     263                                Gosford Park     4.5     3.576528
19999     288                                        Bean     3.0     3.052533

[20000 rows x 4 columns]

In [ ]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

true_y = np.array(test_data['rating'])
pred_y = np.array(test_data['pred_rating'])

mae = mean_absolute_error(y_true=true_y, y_pred=pred_y)
mse = mean_squared_error(y_true=true_y, y_pred=pred_y)
rmse = np.sqrt(mse)

print(f"MAE  : {str(round(mae, 2))}")
print(f"MSE  : {str(round(mse, 2))}")
print(f"RMSE : {str(round(rmse, 2))}")

MAE  : 0.74
MSE  : 0.85
RMSE : 0.92


In [ ]:
# 모델이 추천한 영화 개수
n_recommends = sum(1 * (pred_y > 4.0))
n_recommends

904

In [ ]:
n_movies = df['title'].nunique()

In [ ]:
# Coverage
n_recommends / n_movies

0.09603739509189418

In [ ]:
def get_precision(true_y, pred_y, threshold):
    trues = 1 * (true_y >= threshold)
    n_trues = sum(trues)

    pred_trues = 1 * (pred_y >= threshold)

    true_positive = sum(trues + pred_trues == 2)

    precision = true_positive / n_trues

    return precision

In [ ]:
get_precision(true_y, pred_y, 3)

0.840515381295851

In [ ]:
df_pred_all.to_csv(path + "user_based_cf_prediction.csv", index=False)